- hosts: all
  tasks:
    - shell: "{{ zuul_work_dir }}./hack/setup-kubectl.sh"
    - shell: "{{ zuul_work_dir }}./hack/setup-helm.sh"
    - shell: "{{ zuul_work_dir }}./hack/setup-docker.sh"
    - shell: "{{ zuul_work_dir }}./hack/setup-kind.sh"
    - shell: "{{ zuul_work_dir }}./hack/setup-capo.sh"
