{{- if .Values.serviceMonitor.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "occm.name" . }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- with .Values.commonAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  ports:
  - name: http
    port: 10258
    protocol: TCP
  selector:
    {{- include "occm.controllermanager.matchLabels" . | nindent 4 }}
{{- end }}
