charts:
  - name: cluster-autoscaler
    version: 9.29.1
    repository:
      url: https://kubernetes.github.io/autoscaler
  - name: cilium
    version: 1.15.3
    repository:
      url: https://helm.cilium.io/
  - name: openstack-cloud-controller-manager
    version: 2.34.2
    repository:
      url: https://kubernetes.github.io/cloud-provider-openstack
  - name: openstack-cinder-csi
    version: 2.32.0
    repository:
      url: https://kubernetes.github.io/cloud-provider-openstack
  - name: openstack-manila-csi
    version: 2.32.0
    repository:
      url: https://kubernetes.github.io/cloud-provider-openstack
