apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:
  - path: magnum_cluster_api/charts/vendor
    excludePaths: k8s-keystone-auth
    contents:
      - path: cluster-autoscaler
        helmChart:
          name: cluster-autoscaler
          version: 9.29.1
          repository:
            url: https://kubernetes.github.io/autoscaler
      - path: cilium
        helmChart:
          name: cilium
          version: 1.15.3
          repository:
            url: https://helm.cilium.io/
