controller:
  enabled: true

  replicaCount: 1

  fullnameOverride: ""

  revisionHistoryLimit: 10

  args:
    leaderElection: true
    leaderElectionNamespace: "$(NAMESPACE)"
    httpEndpoint: ":8080"

  image:
    repository: registry.k8s.io/sig-storage/snapshot-controller
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: ""

  imagePullSecrets: []

  podAnnotations: {}

  podLabels: {}

  podSecurityContext: {}
    # fsGroup: 2000

  securityContext:
    capabilities:
      drop:
      - ALL
    readOnlyRootFilesystem: true
    runAsNonRoot: true
    runAsUser: 1000

  resources: {}

  nodeSelector: {}

  tolerations: []

  affinity: {}

  ## Ref: https://kubernetes.io/docs/tasks/run-application/configure-pdb/
  ##
  pdb: {}

  topologySpreadConstraints: []

  rbac:
    # Specifies whether RBAC resources should be created
    create: true

  serviceAccount:
    # Specifies whether a ServiceAccount should be created
    create: true
    name: ""

  serviceMonitor:
    # Specifies whether a ServiceMonitor should be created
    create: false

  volumeSnapshotClasses: []
#    - name: block-snapshot
#      annotations:
#        snapshot.storage.kubernetes.io/is-default-class: "true"
#      driver: cinder.csi.openstack.org
#      deletionPolicy: Delete
#    - name: share-snapshot
#      annotations:
#        snapshot.storage.kubernetes.io/is-default-class: "true"
#      driver: manila.csi.openstack.org
#      deletionPolicy: Delete

  priorityClassName: ""
    # Specifies wether a Priority Class should be attached to deployment pods

  # Change `hostNetwork` to `true` when you want the pod to share its host's network namespace.
  hostNetwork: false

  # DNS settings for the controller pod. https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#pod-dns-config
  dnsConfig: {}
  # DNS Policy for controller pod. For Pods running with hostNetwork, set to `ClusterFirstWithHostNet`
  # For further reference: https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#pod-s-dns-policy.
  dnsPolicy: ClusterFirst
