apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: system:{{ include "k8s-keystone-auth.fullname" . }}
  labels:
    {{- include "k8s-keystone-auth.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
      - services
      - pods
    verbs:
      - get
      - list
      - watch
