apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "k8s-keystone-auth.fullname" . }}-sync
  labels:
    {{- include "k8s-keystone-auth.labels" . | nindent 4 }}
data:
  syncConfig: |
{{ .Values.conf.sync_config | indent 4 }}
