apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "k8s-keystone-auth.fullname" . }}-policy
  labels:
    {{- include "k8s-keystone-auth.labels" . | nindent 4 }}
data:
  policies: {{ toJson .Values.conf.policy | quote }}
