apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "k8s-keystone-auth.fullname" . }}
  labels:
    {{- include "k8s-keystone-auth.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "k8s-keystone-auth.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "k8s-keystone-auth.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "k8s-keystone-auth.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - ./bin/k8s-keystone-auth
            - --tls-cert-file
            - /etc/kubernetes/pki/apiserver.crt
            - --tls-private-key-file
            - /etc/kubernetes/pki/apiserver.key
            - --policy-configmap-name
            - {{ include "k8s-keystone-auth.fullname" . }}-policy
            - --keystone-url
            - {{ .Values.conf.auth_url }}
            - --sync-configmap-name
            - {{ include "k8s-keystone-auth.fullname" . }}-sync
            {{- if not (empty .Values.conf.ca_cert) }}
            - --keystone-ca-file
            - /etc/kubernetes/cloud_ca.crt
            {{- end }}
            - --listen
            - 127.0.0.1:8443
          ports:
            - name: https
              containerPort: {{ .Values.service.port }}
              hostPort: {{ .Values.service.hostPort }}
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            {{- if not (empty .Values.conf.ca_cert) }}
            - mountPath: /etc/kubernetes/cloud_ca.crt
              subPath: cloud_ca.crt
              name: cloud-cert
              readOnly: true
            {{- end }}
            - mountPath: /etc/kubernetes/pki
              name: k8s-certs
              readOnly: true
          {{- with .Values.volumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
      hostNetwork: true
      volumes:
        {{- if not (empty .Values.conf.ca_cert) }}
        - name: cloud-cert
          secret:
            secretName: {{ include "k8s-keystone-auth.fullname" . }}-ca
            defaultMode: 0444
        {{- end }}
        - hostPath:
            path: /etc/kubernetes/pki
            type: DirectoryOrCreate
          name: k8s-certs
      {{- with .Values.volumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
