apiVersion: v1
kind: Service
metadata:
  name: {{ include "k8s-keystone-auth.fullname" . }}
  labels:
    {{- include "k8s-keystone-auth.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: https
  selector:
    {{- include "k8s-keystone-auth.selectorLabels" . | nindent 4 }}
