apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: openstack-manila-csi
    component: nodeplugin
  name: openstack-manila-csi-nodeplugin
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: openstack-manila-csi
      component: nodeplugin
  template:
    metadata:
      labels:
        app: openstack-manila-csi
        component: nodeplugin
    spec:
      containers:
      - args:
        - --csi-address=/csi/csi.sock
        - --kubelet-registration-path=/var/lib/kubelet/plugins/manila.csi.openstack.org/csi.sock
        env:
        - name: KUBE_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        image: registry.k8s.io/sig-storage/csi-node-driver-registrar:v2.4.0
        imagePullPolicy: IfNotPresent
        lifecycle:
          preStop:
            exec:
              command:
              - /bin/sh
              - -c
              - rm -rf /registration/manila.csi.openstack.org /registration/manila.csi.openstack.org-reg.sock
        name: registrar
        volumeMounts:
        - mountPath: /csi
          name: plugin-dir
        - mountPath: /registration
          name: registration-dir
      - command:
        - /bin/sh
        - -c
        - /bin/manila-csi-plugin --nodeid=$(NODE_ID) --endpoint=$(CSI_ENDPOINT) --drivername=$(DRIVER_NAME)
          --share-protocol-selector=$(MANILA_SHARE_PROTO) --fwdendpoint=$(FWD_CSI_ENDPOINT)
        env:
        - name: DRIVER_NAME
          value: manila.csi.openstack.org
        - name: NODE_ID
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: CSI_ENDPOINT
          value: unix:///var/lib/kubelet/plugins/manila.csi.openstack.org/csi.sock
        - name: FWD_CSI_ENDPOINT
          value: unix:///var/lib/kubelet/plugins/csi-nfsplugin/csi.sock
        - name: MANILA_SHARE_PROTO
          value: NFS
        image: registry.k8s.io/provider-os/manila-csi-plugin:latest
        imagePullPolicy: IfNotPresent
        name: nodeplugin
        securityContext:
          allowPrivilegeEscalation: true
          capabilities:
            add:
            - SYS_ADMIN
          privileged: true
        volumeMounts:
        - mountPath: /var/lib/kubelet/plugins/manila.csi.openstack.org
          name: plugin-dir
        - mountPath: /var/lib/kubelet/plugins/csi-nfsplugin
          name: fwd-plugin-dir
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      serviceAccountName: openstack-manila-csi-nodeplugin
      tolerations:
      - operator: Exists
      volumes:
      - hostPath:
          path: /var/lib/kubelet/plugins_registry
          type: Directory
        name: registration-dir
      - hostPath:
          path: /var/lib/kubelet/plugins/manila.csi.openstack.org
          type: DirectoryOrCreate
        name: plugin-dir
      - hostPath:
          path: /var/lib/kubelet/plugins/csi-nfsplugin
          type: DirectoryOrCreate
        name: fwd-plugin-dir
