apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: openstack-manila-csi
    component: controllerplugin
  name: openstack-manila-csi-controllerplugin
  namespace: kube-system
---
aggregationRule:
  clusterRoleSelectors:
  - matchLabels:
      rbac.manila.csi.openstack.org/aggregate-to-openstack-manila-csi-controllerplugin: 'true'
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app: openstack-manila-csi
    component: controllerplugin
  name: openstack-manila-csi-controllerplugin
rules: []
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app: openstack-manila-csi
    component: controllerplugin
    rbac.manila.csi.openstack.org/aggregate-to-openstack-manila-csi-controllerplugin: 'true'
  name: openstack-manila-csi-controllerplugin-rules
rules:
- apiGroups:
  - ''
  resources:
  - nodes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ''
  resources:
  - secrets
  verbs:
  - get
  - list
- apiGroups:
  - ''
  resources:
  - persistentvolumes
  verbs:
  - get
  - list
  - watch
  - create
  - delete
  - patch
- apiGroups:
  - ''
  resources:
  - persistentvolumeclaims
  verbs:
  - get
  - list
  - watch
  - update
- apiGroups:
  - ''
  resources:
  - persistentvolumeclaims/status
  verbs:
  - patch
- apiGroups:
  - ''
  resources:
  - events
  verbs:
  - list
  - watch
  - create
  - update
  - patch
- apiGroups:
  - storage.k8s.io
  resources:
  - storageclasses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - storage.k8s.io
  resources:
  - csinodes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - snapshot.storage.k8s.io
  resources:
  - volumesnapshotclasses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - snapshot.storage.k8s.io
  resources:
  - volumesnapshots
  verbs:
  - get
  - list
- apiGroups:
  - snapshot.storage.k8s.io
  resources:
  - volumesnapshotcontents
  verbs:
  - create
  - get
  - list
  - watch
  - update
  - delete
  - patch
- apiGroups:
  - snapshot.storage.k8s.io
  resources:
  - volumesnapshotcontents/status
  verbs:
  - update
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app: openstack-manila-csi
    component: controllerplugin
  name: openstack-manila-csi-controllerplugin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: openstack-manila-csi-controllerplugin
subjects:
- kind: ServiceAccount
  name: openstack-manila-csi-controllerplugin
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app: openstack-manila-csi
    component: controllerplugin
  name: openstack-manila-csi-controllerplugin
  namespace: kube-system
rules:
- apiGroups:
  - ''
  resources:
  - endpoints
  verbs:
  - get
  - watch
  - list
  - delete
  - update
  - create
- apiGroups:
  - ''
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app: openstack-manila-csi
    component: controllerplugin
  name: openstack-manila-csi-controllerplugin
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: openstack-manila-csi-controllerplugin
subjects:
- kind: ServiceAccount
  name: openstack-manila-csi-controllerplugin
  namespace: kube-system
