apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: openstack-manila-csi
    component: nodeplugin
  name: openstack-manila-csi-nodeplugin
  namespace: kube-system
---
aggregationRule:
  clusterRoleSelectors:
  - matchLabels:
      rbac.manila.csi.openstack.org/aggregate-to-openstack-manila-csi-nodeplugin: 'true'
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app: openstack-manila-csi
    component: nodeplugin
  name: openstack-manila-csi-nodeplugin
rules: []
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app: openstack-manila-csi
    component: nodeplugin
    rbac.manila.csi.openstack.org/aggregate-to-openstack-manila-csi-nodeplugin: 'true'
  name: openstack-manila-csi-nodeplugin-rules
rules:
- apiGroups:
  - ''
  resources:
  - configmaps
  verbs:
  - get
  - list
- apiGroups:
  - ''
  resources:
  - nodes
  verbs:
  - get
  - list
  - update
- apiGroups:
  - ''
  resources:
  - namespaces
  verbs:
  - get
  - list
- apiGroups:
  - ''
  resources:
  - persistentvolumes
  verbs:
  - get
  - list
  - watch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app: openstack-manila-csi
    component: nodeplugin
  name: openstack-manila-csi-nodeplugin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: openstack-manila-csi-nodeplugin
subjects:
- kind: ServiceAccount
  name: openstack-manila-csi-nodeplugin
  namespace: kube-system
