- hosts: all
  roles:
    - ensure-rust
    - ensure-uv

  tasks:
    - name: Install build dependencies
      ansible.builtin.apt:
        name:
          - build-essential
          - pkg-config
          - libssl-dev
        state: present
        update_cache: true
      become: true

    - name: Run no-op command to build module
      ansible.builtin.command: uv run python3 --version
      args:
        chdir: "{{ zuul.project.src_dir }}"

  vars:
    ensure_uv_global_symlink: true
