- hosts: all
  roles:
    - ensure-rust
    - ensure-uv

  tasks:
    - name: Run no-op command to build module
      ansible.builtin.command: uv run python3 --version
      args:
        chdir: "{{ zuul.project.src_dir }}"

  vars:
    ensure_uv_global_symlink: true
