- hosts: all
  tasks:
    - name: Return built artifacts to Zuul
      zuul_return:
        data:
          zuul:
            artifacts:
              - name: "Sonobuoy Results"
                url: "artifacts/sonobuoy-results.tar.gz"
                metadata:
                  type: tarball

    - name: Gather all pod logs from KinD
      become: true
      ignore_errors: true
      block:
        - name: Get the Docker volume ID
          ansible.builtin.command: docker volume ls -q
          register: volume_id

        - name: Copy all of the pod logs
          ansible.builtin.copy:
            src: "/var/lib/docker/volumes/{{ volume_id.stdout_lines[0] }}/_data/log/pods"
            dest: "{{ zuul_output_dir }}/logs"
            owner: "{{ ansible_user }}"
            group: "{{ ansible_user }}"
            remote_src: true
