- hosts: all
  tasks:
    - name: Return built artifacts to Zuul
      zuul_return:
        data:
          zuul:
            artifacts:
              - name: "Sonobuoy Results"
                url: "artifacts/sonobuoy-results.tar.gz"
                metadata:
                  type: tarball
