- hosts: all
   tasks:
    - debug: var=zuul

    # - shell: "./hack/stack.sh"
    #   args:
    #     chdir: "{{ zuul.project.src_dir }}"
 
    # - shell: "{{ zuul.project.src_dir }}/hack/run-integration-tests.sh"
    #   environment:
    #     OS_DISTRO: "{{ os_distro }}"
    #     KUBE_TAG: "{{ kube_tag }}"
    #     NODE_COUNT: 2
