- hosts: all
  tasks:
    - name: Fetch artifact
      get_url:
        url: "{{ item.url }}"
        dest: "{{ zuul.project.src_dir }}/{{ image_operating_system }}-kube-{{ kube_tag }}.qcow2"
      register: fetch_artifact
      loop: "{{ zuul.artifacts }}"
      when:
        - item.name is defined
        - item.name == "{{ image_operating_system }}-kube-{{ kube_tag }}.qcow2"

    - name: Install DevStack
      ansible.builtin.include_role:
        name: orchestrate-devstack

    - name: Install kubectl CLI
      ansible.builtin.shell: ./hack/setup-kubectl.sh
      args:
        chdir: "{{ zuul.project.src_dir }}"

    - name: Install Helm
      ansible.builtin.shell: ./hack/setup-helm.sh
      args:
        chdir: "{{ zuul.project.src_dir }}"

    - name: Install Docker
      ansible.builtin.shell: ./hack/setup-docker.sh
      args:
        chdir: "{{ zuul.project.src_dir }}"

    - name: Install Kind
      ansible.builtin.shell: ./hack/setup-kind.sh
      args:
        chdir: "{{ zuul.project.src_dir }}"

    - name: Install CAPI/CAPO
      ansible.builtin.shell: ./hack/setup-capo.sh
      args:
        chdir: "{{ zuul.project.src_dir }}"

    - name: Install "magnum-cluster-api"
      ansible.builtin.pip:
        name: "/{{ zuul.project.src_dir }}"
        extra_args: --constraint /opt/stack/requirements/upper-constraints.txt
        editable: true

    - name: Restart Magnum services
      ansible.builtin.service:
        name: "{{ item }}"
        state: started
      loop:
        - devstack@magnum-api
        - devstack@magnum-cond

    - shell: "./hack/run-integration-tests.sh"
      args:
        chdir: "{{ zuul.project.src_dir }}"
      environment:
        OS_DISTRO: "{{ image_os_distro }}"
        KUBE_TAG: "{{ kube_tag }}"
        NODE_COUNT: 2
        NETWORK_DRIVER: "{{ network_driver }}"
        IMAGE_NAME: "{{ devstack_localrc['MAGNUM_GUEST_IMAGE_URL'].split('/')[-1].split('.')[0] }}"

    - name: Copy Sonobuoy results to output folder
      copy:
        src: "{{ zuul.project.src_dir }}/sonobuoy-results.tar.gz"
        dest: "{{ zuul_output_dir }}/artifacts/sonobuoy-results.tar.gz"
        remote_src: true
