[package]
name = "helm"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = "1.0.218"
serde_yaml = "0.9.34"
thiserror = "2.0.11"

[dev-dependencies]
serde = { version = "1.0.218", features = ["derive"] }
