- hosts: all
  tasks:
    - name: Return built artifacts to Zuul
      zuul_return:
        data:
          zuul:
            artifacts:
              - name: "{{ os_distro }}-kube-{{ kube_tag }}.qcow2"
                url: "artifacts/{{ os_distro }}-kube-{{ kube_tag }}.qcow2"
