- project:
    check:
      jobs:
        - magnum-cluster-api-hydrophone-v1.32.12-calico
        - magnum-cluster-api-hydrophone-v1.32.12-cilium
        - magnum-cluster-api-hydrophone-v1.33.8-calico
        - magnum-cluster-api-hydrophone-v1.33.8-cilium
        - magnum-cluster-api-hydrophone-v1.34.4-calico
        - magnum-cluster-api-hydrophone-v1.34.4-cilium
        - magnum-cluster-api-hydrophone-v1.35.1-calico
        - magnum-cluster-api-hydrophone-v1.35.1-cilium
    gate:
      jobs:
        - magnum-cluster-api-hydrophone-v1.32.12-calico
        - magnum-cluster-api-hydrophone-v1.32.12-cilium
        - magnum-cluster-api-hydrophone-v1.33.8-calico
        - magnum-cluster-api-hydrophone-v1.33.8-cilium
        - magnum-cluster-api-hydrophone-v1.34.4-calico
        - magnum-cluster-api-hydrophone-v1.34.4-cilium
        - magnum-cluster-api-hydrophone-v1.35.1-calico
        - magnum-cluster-api-hydrophone-v1.35.1-cilium
