- project:
    check:
      jobs:
        - magnum-cluster-api-hydrophone-v1.33.12-calico
        - magnum-cluster-api-hydrophone-v1.33.12-cilium
        - magnum-cluster-api-hydrophone-v1.34.8-calico
        - magnum-cluster-api-hydrophone-v1.34.8-cilium
        - magnum-cluster-api-hydrophone-v1.35.5-calico
        - magnum-cluster-api-hydrophone-v1.35.5-cilium
    gate:
      jobs:
        - magnum-cluster-api-hydrophone-v1.33.12-calico
        - magnum-cluster-api-hydrophone-v1.33.12-cilium
        - magnum-cluster-api-hydrophone-v1.34.8-calico
        - magnum-cluster-api-hydrophone-v1.34.8-cilium
        - magnum-cluster-api-hydrophone-v1.35.5-calico
        - magnum-cluster-api-hydrophone-v1.35.5-cilium
