- project:
    check:
      jobs:
        - magnum-cluster-api-tox-functional
        - magnum-cluster-api-tox-unit
    gate:
      jobs:
        - magnum-cluster-api-tox-functional
        - magnum-cluster-api-tox-unit
