- project:
    check:
      jobs:
        - magnum-cluster-api-hydrophone-v1.32.13-calico
        - magnum-cluster-api-hydrophone-v1.32.13-cilium
        - magnum-cluster-api-hydrophone-v1.33.9-calico
        - magnum-cluster-api-hydrophone-v1.33.9-cilium
        - magnum-cluster-api-hydrophone-v1.34.5-calico
        - magnum-cluster-api-hydrophone-v1.34.5-cilium
        - magnum-cluster-api-hydrophone-v1.35.2-calico
        - magnum-cluster-api-hydrophone-v1.35.2-cilium
    gate:
      jobs:
        - magnum-cluster-api-hydrophone-v1.32.13-calico
        - magnum-cluster-api-hydrophone-v1.32.13-cilium
        - magnum-cluster-api-hydrophone-v1.33.9-calico
        - magnum-cluster-api-hydrophone-v1.33.9-cilium
        - magnum-cluster-api-hydrophone-v1.34.5-calico
        - magnum-cluster-api-hydrophone-v1.34.5-cilium
        - magnum-cluster-api-hydrophone-v1.35.2-calico
        - magnum-cluster-api-hydrophone-v1.35.2-cilium
