- project:
    check:
      jobs:
        - magnum-cluster-api-cargo-clippy
        - magnum-cluster-api-cargo-test
        - magnum-cluster-api-chart-vendor
        - magnum-cluster-api-tox-functional
        - magnum-cluster-api-tox-linters
        - magnum-cluster-api-tox-unit
    gate:
      jobs:
        - magnum-cluster-api-cargo-clippy
        - magnum-cluster-api-cargo-test
        - magnum-cluster-api-chart-vendor
        - magnum-cluster-api-tox-functional
        - magnum-cluster-api-tox-linters
        - magnum-cluster-api-tox-unit
    templates:
      - magnum-cluster-api-flatcar
      - magnum-cluster-api-rockylinux-8
      - magnum-cluster-api-rockylinux-9
      - magnum-cluster-api-ubuntu-2204
