- project:
    check:
      jobs:
        - magnum-cluster-api-unit
        - magnum-cluster-api-functional
    templates:
      - magnum-cluster-api-flatcar
      - magnum-cluster-api-rockylinux-8
      - magnum-cluster-api-rockylinux-9
      - magnum-cluster-api-ubuntu-2204
