- project:
    check:
      jobs:
        - magnum-cluster-api-chart-vendor
        - magnum-cluster-api-linters
        - magnum-cluster-api-unit
        - magnum-cluster-api-functional
    templates:
      - magnum-cluster-api-flatcar
      - magnum-cluster-api-rockylinux-8
      - magnum-cluster-api-rockylinux-9
      - magnum-cluster-api-tempest-ubuntu-2204
      #- magnum-cluster-api-sonobuoy-ubuntu-2204
