- project:
    check:
      jobs:
        - magnum-cluster-api-chart-vendor
        - magnum-cluster-api-tox-linters
        - magnum-cluster-api-tox-unit
        - magnum-cluster-api-tox-functional
    gate:
      jobs:
        - magnum-cluster-api-chart-vendor
        - magnum-cluster-api-tox-linters
        - magnum-cluster-api-tox-unit
        - magnum-cluster-api-tox-functional
    templates:
      - magnum-cluster-api-flatcar
      - magnum-cluster-api-rockylinux-8
      - magnum-cluster-api-rockylinux-9
      - magnum-cluster-api-ubuntu-2204
