name: ci

on:
  pull_request:
  workflow_dispatch:
  push:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

permissions: {}

jobs:
  cargo:
    uses: vexxhost/github-actions/.github/workflows/cargo.yml@1792807163c61621500aaf37d61363646eede63e # main

  build:
    runs-on: ubuntu-24.04${{ matrix.target == 'aarch64' && '-arm' || '' }}
    timeout-minutes: 5
    strategy:
      fail-fast: false
      matrix:
        target: [x86_64, aarch64]
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@a90bcbc6539c36a85cdfeb73f7e2f433735f215b # v2.15.0
        with:
          egress-policy: audit

      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
      - uses: rui314/setup-mold@725a8794d15fc7563f59595bd9556495c0564878 # v1
      - uses: step-security/rust-cache@9be15b830520fab0ec3939586e917e4855cf76bd # v2.8.3
      - run: rustup show
      - uses: PyO3/maturin-action@86b9d133d34bc1b40018696f782949dac11bd380 # v1.49.4
        with:
          maturin-version: v1.9.6
          command: build
          manylinux: "2_28"
          args: --release --sdist
          sccache: "true"
          target: ${{ matrix.target }}
      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: wheel-${{ matrix.target }}
          if-no-files-found: error
          path: |
            target/wheels/*.whl
            target/wheels/*.tar.gz

  coinstall:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    needs: build
    strategy:
      fail-fast: false
      matrix:
        openstack-version:
          - "2023.1"
          - "2023.2"
          - "2024.1"
          - "2024.2"
          - "2025.1"
          - "master"
        python-version:
          - "3.10"
          - "3.11"
          - "3.12"
        include:
          - openstack-version: "zed"
            python-version: "3.10"
        exclude:
          - openstack-version: "2023.1"
            python-version: "3.12"
          - openstack-version: "2023.2"
            python-version: "3.12"
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@a90bcbc6539c36a85cdfeb73f7e2f433735f215b # v2.15.0
        with:
          egress-policy: audit

      - uses: step-security/setup-uv@ccf0a26ce9117d9e99292b0ce953ea5d9ffe778e # v7.3.0
        with:
          ignore-empty-workdir: true
          python-version: ${{ matrix.python-version }}
      - uses: actions/download-artifact@634f93cb2916e3fdff6788551b99b062d0335ce0 # v5.0.0
        with:
          name: wheel-x86_64
      - run: |
          uv venv
          uv pip install --constraint https://releases.openstack.org/constraints/upper/${{ matrix.openstack-version }} ./*.whl

  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@a90bcbc6539c36a85cdfeb73f7e2f433735f215b # v2.15.0
        with:
          egress-policy: audit

      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
        with:
          ref: ${{ github.head_ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name || github.repository }}
          token: ${{ secrets.VEXXHOST_BOT_PAT || github.token }}
      - uses: pre-commit/action@2c7b3805fd2a0fd8c1884dcaebf91fc102a13ecd # v3.0.1
      - uses: step-security/git-auto-commit-action@905c3cd6e9ed2b67b4d46ff401fdb6d745d0ff9d # v7.1.0
        if: github.event_name == 'pull_request' && github.event.pull_request.user.id == '29139614' && always()
        with:
          commit_message: "chore: apply pre-commit hook updates"
          commit_author: "renovate[bot] <29139614+renovate[bot]@users.noreply.github.com>"

  chart-vendor:
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@a90bcbc6539c36a85cdfeb73f7e2f433735f215b # v2.15.0
        with:
          egress-policy: audit

      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
      - uses: vexxhost/chart-vendor@1647518769fa4e8af6806e6e8863e60c8737e7c6 # main
        with:
          charts-root: magnum_cluster_api/charts
