name: image

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

on:
  workflow_dispatch:
    inputs:
      image_push:
        type: boolean
        description: 'Push images to Container Registry'
        required: false
        default: false
  pull_request:
    paths-ignore:
      - "docs/**"
      - README.md
  push:
    branches:
      - main
    tags:
      - "v*"
    paths-ignore:
      - "docs/**"
      - README.md

permissions:
  contents: read
  packages: write

jobs:
  ## NOTE(okozachenko1203): Disable this job for now.
  # service:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: earthly/actions-setup@43211c7a0eae5344d6d79fb4aaf209c8f8866203 # v1
  #       with:
  #         github-token: ${{ secrets.GITHUB_TOKEN }}

  #     - name: Checkout project
  #       uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3

  #     - name: Authenticate with Quay.io
  #       uses: docker/login-action@465a07811f14bebb1938fbed4728c6a1ff8901fc # v2
  #       if: ${{ github.event_name == 'push' || (github.event_name == 'workflow_dispatch' && inputs.image_push == true) }}
  #       with:
  #         registry: quay.io
  #         username: ${{ secrets.QUAY_USERNAME }}
  #         password: ${{ secrets.QUAY_ROBOT_TOKEN }}

  #     - name: Build image
  #       run: earthly +image --GIT_SHA ${{ github.sha }}
  #       env:
  #         EARTHLY_CI: true
  #         EARTHLY_PUSH: "${{ github.event_name == 'push' }}"

  registry:
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@a90bcbc6539c36a85cdfeb73f7e2f433735f215b # v2.15.0
        with:
          egress-policy: audit

      - name: Configure Buildkit
        uses: step-security/setup-buildx-action@c60a792b446ef83310733d5cd9d0c8d6870d043f # v3.12.0

      - name: Checkout project
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1

      - name: Generate image metadata
        id: meta
        uses: docker/metadata-action@c299e40c65443455700f0fdfc63efafe5b349051 # v5.10.0
        with:
          images: quay.io/vexxhost/magnum-cluster-api-registry
          tags: |
            type=semver,pattern={{version}}
            type=sha
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Authenticate with Quay.io
        uses: step-security/docker-login-action@6aa05fe688caf2c58e784663f01b3415ced503e8 # v3.7.0
        if: ${{ github.event_name == 'push' || github.event_name == 'tag' || (github.event_name == 'workflow_dispatch' && inputs.image_push == true) }}
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_ROBOT_TOKEN }}

      - name: Build image
        uses: step-security/docker-build-push-action@a8c3d08b23f8be6aeed43eb1a14ce6fe51284438 # v6.18.0
        with:
          target: registry
          push: ${{ github.event_name == 'push' || github.event_name == 'tag' || inputs.image_push == true }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
