name: release-please

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: write
  pull-requests: write
  issues: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@f808768d1510423e83855289c910610ca9b43176 # v2.17.0
        with:
          egress-policy: audit

      - uses: googleapis/release-please-action@16a9c90856f42705d54a6fda1823352bdc62cf38 # v4.4.0
        id: release
        with:
          release-type: rust
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        if: ${{ steps.release.outputs.release_created }}
      - name: Build package (x86_64)
        if: ${{ steps.release.outputs.release_created }}
        uses: PyO3/maturin-action@e83996d129638aa358a18fbd1dfb82f0b0fb5d3b # v1.51.0
        with:
          maturin-version: v1.9.6
          command: publish
          args: --non-interactive --skip-existing
          manylinux: '2_28'
          target: x86_64
      - name: Build package (aarch64)
        if: ${{ steps.release.outputs.release_created }}
        uses: PyO3/maturin-action@e83996d129638aa358a18fbd1dfb82f0b0fb5d3b # v1.51.0
        with:
          maturin-version: v1.9.6
          command: publish
          args: --non-interactive --skip-existing
          manylinux: '2_28'
          target: aarch64
